// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: authors.sql

package store

import (
	"context"
	"strings"
)

const deleteBookAuthors = `-- name: DeleteBookAuthors :exec
DELETE FROM book_authors WHERE book_id = ?
`

func (q *Queries) DeleteBookAuthors(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookAuthors, bookID)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name FROM authors WHERE id = ?
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name FROM authors WHERE name = ?
`

func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertAuthor = `-- name: InsertAuthor :one
INSERT INTO authors (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) InsertAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRowContext(ctx, insertAuthor, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertBookAuthor = `-- name: InsertBookAuthor :exec
INSERT OR IGNORE INTO book_authors (book_id, author_id) VALUES (?, ?)
`

type InsertBookAuthorParams struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) InsertBookAuthor(ctx context.Context, arg InsertBookAuthorParams) error {
	_, err := q.db.ExecContext(ctx, insertBookAuthor, arg.BookID, arg.AuthorID)
	return err
}

const listAuthors = `-- name: ListAuthors :many
SELECT
    a.id,
    a.name,
    COUNT(b.id) AS book_count,
    CAST(COALESCE(SUM(CASE WHEN b.read_status = 'read' THEN 1 ELSE 0 END), 0) AS INTEGER) AS read_count,
    CAST(COALESCE(SUM(CASE WHEN b.read_status = 'unread' THEN COALESCE(b.want_rating, 0) ELSE 0 END), 0) AS INTEGER) AS unread_want_sum,
    CAST(COALESCE(SUM(CASE WHEN b.read_status = 'unread' AND (b.owned_physical = 1 OR b.owned_digital = 1) THEN 1 ELSE 0 END), 0) AS INTEGER) AS unread_owned,
    CAST(COALESCE(SUM(CASE WHEN b.read_status = 'unread' AND b.owned_physical = 0 AND b.owned_digital = 0 THEN 1 ELSE 0 END), 0) AS INTEGER) AS unread_coveting
FROM authors a
LEFT JOIN book_authors ba ON ba.author_id = a.id
LEFT JOIN books b ON b.id = ba.book_id
GROUP BY a.id
ORDER BY unread_want_sum DESC, read_count DESC, a.name COLLATE NOCASE
`

type ListAuthorsRow struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	BookCount      int64  `json:"book_count"`
	ReadCount      int64  `json:"read_count"`
	UnreadWantSum  int64  `json:"unread_want_sum"`
	UnreadOwned    int64  `json:"unread_owned"`
	UnreadCoveting int64  `json:"unread_coveting"`
}

func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BookCount,
			&i.ReadCount,
			&i.UnreadWantSum,
			&i.UnreadOwned,
			&i.UnreadCoveting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsForBooks = `-- name: ListAuthorsForBooks :many
SELECT ba.book_id, a.id AS author_id, a.name
FROM book_authors ba
JOIN authors a ON a.id = ba.author_id
WHERE ba.book_id IN (/*SLICE:book_ids*/?)
ORDER BY a.name COLLATE NOCASE
`

type ListAuthorsForBooksRow struct {
	BookID   int64  `json:"book_id"`
	AuthorID int64  `json:"author_id"`
	Name     string `json:"name"`
}

func (q *Queries) ListAuthorsForBooks(ctx context.Context, bookIds []int64) ([]ListAuthorsForBooksRow, error) {
	query := listAuthorsForBooks
	var queryParams []interface{}
	if len(bookIds) > 0 {
		for _, v := range bookIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:book_ids*/?", strings.Repeat(",?", len(bookIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:book_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsForBooksRow
	for rows.Next() {
		var i ListAuthorsForBooksRow
		if err := rows.Scan(&i.BookID, &i.AuthorID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookAuthors = `-- name: ListBookAuthors :many
SELECT ba.book_id, a.id AS author_id, a.name
FROM book_authors ba
JOIN authors a ON a.id = ba.author_id
ORDER BY a.name COLLATE NOCASE
`

type ListBookAuthorsRow struct {
	BookID   int64  `json:"book_id"`
	AuthorID int64  `json:"author_id"`
	Name     string `json:"name"`
}

func (q *Queries) ListBookAuthors(ctx context.Context) ([]ListBookAuthorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listBookAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookAuthorsRow
	for rows.Next() {
		var i ListBookAuthorsRow
		if err := rows.Scan(&i.BookID, &i.AuthorID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByAuthor = `-- name: ListBooksByAuthor :many
SELECT
    b.id, b.title, b.subtitle, b.isbn, b.published_year, b.description, b.cover_path,
    b.series_name, b.series_index, b.owned_physical, b.owned_digital, b.read_status,
    b.want_rating, b.quality_rating, b.calibre_id, b.created_at, b.updated_at
FROM books b
JOIN book_authors ba ON ba.book_id = b.id
WHERE ba.author_id = ?
ORDER BY b.title COLLATE NOCASE
`

func (q *Queries) ListBooksByAuthor(ctx context.Context, authorID int64) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Isbn,
			&i.PublishedYear,
			&i.Description,
			&i.CoverPath,
			&i.SeriesName,
			&i.SeriesIndex,
			&i.OwnedPhysical,
			&i.OwnedDigital,
			&i.ReadStatus,
			&i.WantRating,
			&i.QualityRating,
			&i.CalibreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadCountByAuthor = `-- name: ListReadCountByAuthor :many
SELECT ba.author_id, COUNT(*) AS read_count
FROM book_authors ba
JOIN books b ON b.id = ba.book_id
WHERE b.read_status = 'read'
GROUP BY ba.author_id
`

type ListReadCountByAuthorRow struct {
	AuthorID  int64 `json:"author_id"`
	ReadCount int64 `json:"read_count"`
}

func (q *Queries) ListReadCountByAuthor(ctx context.Context) ([]ListReadCountByAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, listReadCountByAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadCountByAuthorRow
	for rows.Next() {
		var i ListReadCountByAuthorRow
		if err := rows.Scan(&i.AuthorID, &i.ReadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
