// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package store

import (
	"context"
)

const getBook = `-- name: GetBook :one
SELECT
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
FROM books
WHERE id = ?
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Isbn,
		&i.PublishedYear,
		&i.Description,
		&i.CoverPath,
		&i.SeriesName,
		&i.SeriesIndex,
		&i.OwnedPhysical,
		&i.OwnedDigital,
		&i.ReadStatus,
		&i.WantRating,
		&i.QualityRating,
		&i.CalibreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByCalibreID = `-- name: GetBookByCalibreID :one
SELECT
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
FROM books
WHERE calibre_id = ?
`

func (q *Queries) GetBookByCalibreID(ctx context.Context, calibreID *int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByCalibreID, calibreID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Isbn,
		&i.PublishedYear,
		&i.Description,
		&i.CoverPath,
		&i.SeriesName,
		&i.SeriesIndex,
		&i.OwnedPhysical,
		&i.OwnedDigital,
		&i.ReadStatus,
		&i.WantRating,
		&i.QualityRating,
		&i.CalibreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookByISBN = `-- name: GetBookByISBN :one
SELECT
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
FROM books
WHERE isbn = ? AND isbn != ''
LIMIT 1
`

func (q *Queries) GetBookByISBN(ctx context.Context, isbn *string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByISBN, isbn)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Isbn,
		&i.PublishedYear,
		&i.Description,
		&i.CoverPath,
		&i.SeriesName,
		&i.SeriesIndex,
		&i.OwnedPhysical,
		&i.OwnedDigital,
		&i.ReadStatus,
		&i.WantRating,
		&i.QualityRating,
		&i.CalibreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBook = `-- name: InsertBook :one
INSERT INTO books (
    title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, datetime('now'), datetime('now')
)
RETURNING
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
`

type InsertBookParams struct {
	Title         string   `json:"title"`
	Subtitle      *string  `json:"subtitle"`
	Isbn          *string  `json:"isbn"`
	PublishedYear *int64   `json:"published_year"`
	Description   *string  `json:"description"`
	CoverPath     *string  `json:"cover_path"`
	SeriesName    *string  `json:"series_name"`
	SeriesIndex   *float64 `json:"series_index"`
	OwnedPhysical int64    `json:"owned_physical"`
	OwnedDigital  int64    `json:"owned_digital"`
	ReadStatus    string   `json:"read_status"`
	WantRating    *int64   `json:"want_rating"`
	QualityRating *float64 `json:"quality_rating"`
	CalibreID     *int64   `json:"calibre_id"`
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, insertBook,
		arg.Title,
		arg.Subtitle,
		arg.Isbn,
		arg.PublishedYear,
		arg.Description,
		arg.CoverPath,
		arg.SeriesName,
		arg.SeriesIndex,
		arg.OwnedPhysical,
		arg.OwnedDigital,
		arg.ReadStatus,
		arg.WantRating,
		arg.QualityRating,
		arg.CalibreID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Isbn,
		&i.PublishedYear,
		&i.Description,
		&i.CoverPath,
		&i.SeriesName,
		&i.SeriesIndex,
		&i.OwnedPhysical,
		&i.OwnedDigital,
		&i.ReadStatus,
		&i.WantRating,
		&i.QualityRating,
		&i.CalibreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT
    b.id, b.title, b.subtitle, b.isbn, b.published_year, b.description, b.cover_path,
    b.series_name, b.series_index, b.owned_physical, b.owned_digital, b.read_status,
    b.want_rating, b.quality_rating, b.calibre_id, b.created_at, b.updated_at
FROM books b
WHERE (?1 IS NULL OR b.read_status = ?1)
  AND (?2 IS NULL OR b.want_rating >= ?2)
  AND (?3 IS NULL OR EXISTS (
        SELECT 1 FROM book_piles bp WHERE bp.book_id = b.id AND bp.pile_id = ?3))
  AND (?4 IS NULL OR EXISTS (
        SELECT 1 FROM book_collections bc WHERE bc.book_id = b.id AND bc.collection_id = ?4))
  AND (?5 IS NULL OR EXISTS (
        SELECT 1 FROM book_genres bg WHERE bg.book_id = b.id AND bg.genre_id = ?5))
  AND (?6 IS NULL OR EXISTS (
        SELECT 1 FROM book_authors ba WHERE ba.book_id = b.id AND ba.author_id = ?6))
  AND (
        ?7 IS NULL
        OR (?7 = 'physical' AND b.owned_physical = 1 AND b.owned_digital = 0)
        OR (?7 = 'digital' AND b.owned_digital = 1 AND b.owned_physical = 0)
        OR (?7 = 'both' AND b.owned_physical = 1 AND b.owned_digital = 1)
        OR (?7 = 'coveting' AND b.owned_physical = 0 AND b.owned_digital = 0)
      )
  AND (
        ?8 IS NULL
        OR b.title LIKE '%' || ?8 || '%'
        OR EXISTS (
            SELECT 1 FROM book_authors ba
            JOIN authors a ON a.id = ba.author_id
            WHERE ba.book_id = b.id AND a.name LIKE '%' || ?8 || '%'
        )
      )
`

type ListBooksParams struct {
	ReadStatus   interface{} `json:"read_status"`
	MinWant      interface{} `json:"min_want"`
	PileID       interface{} `json:"pile_id"`
	CollectionID interface{} `json:"collection_id"`
	GenreID      interface{} `json:"genre_id"`
	AuthorID     interface{} `json:"author_id"`
	Ownership    interface{} `json:"ownership"`
	Q            interface{} `json:"q"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks,
		arg.ReadStatus,
		arg.MinWant,
		arg.PileID,
		arg.CollectionID,
		arg.GenreID,
		arg.AuthorID,
		arg.Ownership,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Isbn,
			&i.PublishedYear,
			&i.Description,
			&i.CoverPath,
			&i.SeriesName,
			&i.SeriesIndex,
			&i.OwnedPhysical,
			&i.OwnedDigital,
			&i.ReadStatus,
			&i.WantRating,
			&i.QualityRating,
			&i.CalibreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByNormalizedTitle = `-- name: ListBooksByNormalizedTitle :many
SELECT
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
FROM books
WHERE lower(trim(title)) = lower(trim(?))
`

func (q *Queries) ListBooksByNormalizedTitle(ctx context.Context, trim string) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooksByNormalizedTitle, trim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Isbn,
			&i.PublishedYear,
			&i.Description,
			&i.CoverPath,
			&i.SeriesName,
			&i.SeriesIndex,
			&i.OwnedPhysical,
			&i.OwnedDigital,
			&i.ReadStatus,
			&i.WantRating,
			&i.QualityRating,
			&i.CalibreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadBooks = `-- name: ListUnreadBooks :many
SELECT
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
FROM books
WHERE read_status = 'unread'
`

func (q *Queries) ListUnreadBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Isbn,
			&i.PublishedYear,
			&i.Description,
			&i.CoverPath,
			&i.SeriesName,
			&i.SeriesIndex,
			&i.OwnedPhysical,
			&i.OwnedDigital,
			&i.ReadStatus,
			&i.WantRating,
			&i.QualityRating,
			&i.CalibreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCoverPath = `-- name: SetCoverPath :exec
UPDATE books SET cover_path = ?, updated_at = datetime('now') WHERE id = ?
`

type SetCoverPathParams struct {
	CoverPath *string `json:"cover_path"`
	ID        int64   `json:"id"`
}

func (q *Queries) SetCoverPath(ctx context.Context, arg SetCoverPathParams) error {
	_, err := q.db.ExecContext(ctx, setCoverPath, arg.CoverPath, arg.ID)
	return err
}

const updateBookUserFields = `-- name: UpdateBookUserFields :one
UPDATE books SET
    title = ?,
    subtitle = ?,
    isbn = ?,
    published_year = ?,
    description = ?,
    series_name = ?,
    want_rating = ?,
    read_status = ?,
    owned_physical = ?,
    owned_digital = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
`

type UpdateBookUserFieldsParams struct {
	Title         string  `json:"title"`
	Subtitle      *string `json:"subtitle"`
	Isbn          *string `json:"isbn"`
	PublishedYear *int64  `json:"published_year"`
	Description   *string `json:"description"`
	SeriesName    *string `json:"series_name"`
	WantRating    *int64  `json:"want_rating"`
	ReadStatus    string  `json:"read_status"`
	OwnedPhysical int64   `json:"owned_physical"`
	OwnedDigital  int64   `json:"owned_digital"`
	ID            int64   `json:"id"`
}

func (q *Queries) UpdateBookUserFields(ctx context.Context, arg UpdateBookUserFieldsParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBookUserFields,
		arg.Title,
		arg.Subtitle,
		arg.Isbn,
		arg.PublishedYear,
		arg.Description,
		arg.SeriesName,
		arg.WantRating,
		arg.ReadStatus,
		arg.OwnedPhysical,
		arg.OwnedDigital,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Isbn,
		&i.PublishedYear,
		&i.Description,
		&i.CoverPath,
		&i.SeriesName,
		&i.SeriesIndex,
		&i.OwnedPhysical,
		&i.OwnedDigital,
		&i.ReadStatus,
		&i.WantRating,
		&i.QualityRating,
		&i.CalibreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCalibreMetadata = `-- name: UpdateCalibreMetadata :one
UPDATE books SET
    title = ?,
    isbn = ?,
    published_year = ?,
    description = ?,
    series_name = ?,
    series_index = ?,
    owned_digital = 1,
    quality_rating = ?,
    calibre_id = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING
    id, title, subtitle, isbn, published_year, description, cover_path,
    series_name, series_index, owned_physical, owned_digital, read_status,
    want_rating, quality_rating, calibre_id, created_at, updated_at
`

type UpdateCalibreMetadataParams struct {
	Title         string   `json:"title"`
	Isbn          *string  `json:"isbn"`
	PublishedYear *int64   `json:"published_year"`
	Description   *string  `json:"description"`
	SeriesName    *string  `json:"series_name"`
	SeriesIndex   *float64 `json:"series_index"`
	QualityRating *float64 `json:"quality_rating"`
	CalibreID     *int64   `json:"calibre_id"`
	ID            int64    `json:"id"`
}

func (q *Queries) UpdateCalibreMetadata(ctx context.Context, arg UpdateCalibreMetadataParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateCalibreMetadata,
		arg.Title,
		arg.Isbn,
		arg.PublishedYear,
		arg.Description,
		arg.SeriesName,
		arg.SeriesIndex,
		arg.QualityRating,
		arg.CalibreID,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Subtitle,
		&i.Isbn,
		&i.PublishedYear,
		&i.Description,
		&i.CoverPath,
		&i.SeriesName,
		&i.SeriesIndex,
		&i.OwnedPhysical,
		&i.OwnedDigital,
		&i.ReadStatus,
		&i.WantRating,
		&i.QualityRating,
		&i.CalibreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
