// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: groups.sql

package store

import (
	"context"
)

const deleteBookCollections = `-- name: DeleteBookCollections :exec
DELETE FROM book_collections WHERE book_id = ?
`

func (q *Queries) DeleteBookCollections(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookCollections, bookID)
	return err
}

const deleteBookGenres = `-- name: DeleteBookGenres :exec
DELETE FROM book_genres WHERE book_id = ?
`

func (q *Queries) DeleteBookGenres(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookGenres, bookID)
	return err
}

const deleteBookPiles = `-- name: DeleteBookPiles :exec
DELETE FROM book_piles WHERE book_id = ?
`

func (q *Queries) DeleteBookPiles(ctx context.Context, bookID int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookPiles, bookID)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name FROM collections WHERE id = ?
`

func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCollectionByName = `-- name: GetCollectionByName :one
SELECT id, name FROM collections WHERE name = ?
`

func (q *Queries) GetCollectionByName(ctx context.Context, name string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByName, name)
	var i Collection
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenre = `-- name: GetGenre :one
SELECT id, name FROM genres WHERE id = ?
`

func (q *Queries) GetGenre(ctx context.Context, id int64) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenre, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenreByName = `-- name: GetGenreByName :one
SELECT id, name FROM genres WHERE name = ?
`

func (q *Queries) GetGenreByName(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, getGenreByName, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPile = `-- name: GetPile :one
SELECT id, name FROM piles WHERE id = ?
`

func (q *Queries) GetPile(ctx context.Context, id int64) (Pile, error) {
	row := q.db.QueryRowContext(ctx, getPile, id)
	var i Pile
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPileByName = `-- name: GetPileByName :one
SELECT id, name FROM piles WHERE name = ?
`

func (q *Queries) GetPileByName(ctx context.Context, name string) (Pile, error) {
	row := q.db.QueryRowContext(ctx, getPileByName, name)
	var i Pile
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertBookCollection = `-- name: InsertBookCollection :exec
INSERT OR IGNORE INTO book_collections (book_id, collection_id) VALUES (?, ?)
`

type InsertBookCollectionParams struct {
	BookID       int64 `json:"book_id"`
	CollectionID int64 `json:"collection_id"`
}

func (q *Queries) InsertBookCollection(ctx context.Context, arg InsertBookCollectionParams) error {
	_, err := q.db.ExecContext(ctx, insertBookCollection, arg.BookID, arg.CollectionID)
	return err
}

const insertBookGenre = `-- name: InsertBookGenre :exec
INSERT OR IGNORE INTO book_genres (book_id, genre_id) VALUES (?, ?)
`

type InsertBookGenreParams struct {
	BookID  int64 `json:"book_id"`
	GenreID int64 `json:"genre_id"`
}

func (q *Queries) InsertBookGenre(ctx context.Context, arg InsertBookGenreParams) error {
	_, err := q.db.ExecContext(ctx, insertBookGenre, arg.BookID, arg.GenreID)
	return err
}

const insertBookPile = `-- name: InsertBookPile :exec
INSERT OR IGNORE INTO book_piles (book_id, pile_id) VALUES (?, ?)
`

type InsertBookPileParams struct {
	BookID int64 `json:"book_id"`
	PileID int64 `json:"pile_id"`
}

func (q *Queries) InsertBookPile(ctx context.Context, arg InsertBookPileParams) error {
	_, err := q.db.ExecContext(ctx, insertBookPile, arg.BookID, arg.PileID)
	return err
}

const insertCollection = `-- name: InsertCollection :one
INSERT INTO collections (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) InsertCollection(ctx context.Context, name string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, insertCollection, name)
	var i Collection
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertGenre = `-- name: InsertGenre :one
INSERT INTO genres (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) InsertGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRowContext(ctx, insertGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertPile = `-- name: InsertPile :one
INSERT INTO piles (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) InsertPile(ctx context.Context, name string) (Pile, error) {
	row := q.db.QueryRowContext(ctx, insertPile, name)
	var i Pile
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT id, name FROM collections ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsForBook = `-- name: ListCollectionsForBook :many
SELECT c.id, c.name
FROM collections c
JOIN book_collections bc ON bc.collection_id = c.id
WHERE bc.book_id = ?
ORDER BY c.name COLLATE NOCASE
`

func (q *Queries) ListCollectionsForBook(ctx context.Context, bookID int64) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenres = `-- name: ListGenres :many
SELECT id, name FROM genres ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenresForBook = `-- name: ListGenresForBook :many
SELECT g.id, g.name
FROM genres g
JOIN book_genres bg ON bg.genre_id = g.id
WHERE bg.book_id = ?
ORDER BY g.name COLLATE NOCASE
`

func (q *Queries) ListGenresForBook(ctx context.Context, bookID int64) ([]Genre, error) {
	rows, err := q.db.QueryContext(ctx, listGenresForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPiles = `-- name: ListPiles :many
SELECT id, name FROM piles ORDER BY name COLLATE NOCASE
`

func (q *Queries) ListPiles(ctx context.Context) ([]Pile, error) {
	rows, err := q.db.QueryContext(ctx, listPiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pile
	for rows.Next() {
		var i Pile
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPilesForBook = `-- name: ListPilesForBook :many
SELECT p.id, p.name
FROM piles p
JOIN book_piles bp ON bp.pile_id = p.id
WHERE bp.book_id = ?
ORDER BY p.name COLLATE NOCASE
`

func (q *Queries) ListPilesForBook(ctx context.Context, bookID int64) ([]Pile, error) {
	rows, err := q.db.QueryContext(ctx, listPilesForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pile
	for rows.Next() {
		var i Pile
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
