// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

type Author struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Book struct {
	ID            int64    `json:"id"`
	Title         string   `json:"title"`
	Subtitle      *string  `json:"subtitle"`
	Isbn          *string  `json:"isbn"`
	PublishedYear *int64   `json:"published_year"`
	Description   *string  `json:"description"`
	CoverPath     *string  `json:"cover_path"`
	SeriesName    *string  `json:"series_name"`
	SeriesIndex   *float64 `json:"series_index"`
	OwnedPhysical int64    `json:"owned_physical"`
	OwnedDigital  int64    `json:"owned_digital"`
	ReadStatus    string   `json:"read_status"`
	WantRating    *int64   `json:"want_rating"`
	QualityRating *float64 `json:"quality_rating"`
	CalibreID     *int64   `json:"calibre_id"`
	CreatedAt     string   `json:"created_at"`
	UpdatedAt     string   `json:"updated_at"`
}

type BookAuthor struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}

type BookCollection struct {
	BookID       int64 `json:"book_id"`
	CollectionID int64 `json:"collection_id"`
}

type BookGenre struct {
	BookID  int64 `json:"book_id"`
	GenreID int64 `json:"genre_id"`
}

type BookPile struct {
	BookID int64 `json:"book_id"`
	PileID int64 `json:"pile_id"`
}

type Collection struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Genre struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Pile struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
